language: node_js
node_js:
- '11'
notifications:
  email: false
cache:
  directories:
  - "~/.npm"
  - node_modules
before_deploy:
- npm run test
- npm run build
- pip install --user awscli
deploy:
  provider: script
  script: bash scripts/deploy.sh build algebrain.io
  on:
    branch: master
env:
  global:
  - secure: U16KsSlz9yUWenLFWqTPt7DQgzwwgkGUQEH0qFnRCZaCU1v9CGVBTIhu9CEQln6ZFcYgM/w5JDzugdu1BgbHUoY/mPgyxJE2sjPlTXP5xfFaMFTelGF5RguMnus/A+wzm0Aq44CKV/ZbWDe5M1YMeb7yFTOdTemOKQWZj6yInO1ZkgbawVXSJxPipPdWA7d5mSojybg5B0IrHKQurlT21FiznX2ORKSJPJdYaAqZPt62I5gms4DbBOzPgKFYnAUETUeyT4X8kG/crfJ3QPADiAqmi0yvwn7kiyO56lfl76qGguabFTLWaLgUXOuqWnr9hD0siC1/7IMvr0mRdbPwbVDzrOt9tl387QWIIaBrTk3EH1Yh9rZn+Xudw+PPxvajcZZZJ1TS2GRE0ATkZxch6Ykd+sIpM9/K8qdCKieTsf5gussrMK5uLY2PputYMr/480fZhLGwxxRCzWfqkQkDvhHjomDqhTBwCheQdSnZNCaIWZQeqVTvmy84MmFmle/ijKmTycr6zG7HjvumVABNs+qSUVfvbYO1yB23TkqmTuW5EfH4Ez4icLGooNnzRaU4ECU5l8V8RAirjVLQ2ncn7Eg1DYRWwotDWJ4PdlcxIkRbVZe0+0h9boaECisN492n6pjOebfX8y6MllSPaD2KE46tg3E5+Zk5hmTEVk0+T7E=
  - secure: UiSYjfUDF+NUDL9NHQZNKcCaZbRxSh4w+ahn+K1ZStU3uWKs9rfYwmM4/Cc6hV/AIFS0RCVsoLHYlwljUkDl/Ots8lZuAsQRqcFleM7nqTgUDkmHdlogj2HAiKzK2421OsX+dIC7JPdAaEqXfRcrPnwAL+Nhuz2KZ7P3lw/n0YoeWX3LVqjyu3yrnhTWTsswFqJLT6mceZ4fcZjLneMdv660you7J8FacUBsYkOwbYk+Qr6rxcY1G1/YiDzf5i0Cc4uH/FUfT7j9OYvly9mjY1qfzosAmW6uTads3Fp/IceewVwlxcWA2votK3LrLuLrkwnOYP69Whwr4mO6ametS+UxaU2h8Jg4afJLTDXwVEtsuPTqx2AiWxcpWKivhOj8+vYPvzUD649ZaMLISMV3OG+KsyTjSs5UuzGngzPuIUQLimuTjZCTKfzzQ9ZEoUrcQOZzHxqPiqHR3Kr/RHcMLf/l/rUxbZTQAnvRCTwuCrbEFFP6Qre4LWi5CxfCDR2948a40esKJVP8f6T9M5kC0K3JQGKpB/CJ+dsym/BUILsDK8HB3n1mMiRBZf+nC+A+xg/7wqtAucx4Ewg0d/ONs/JazRfNwjfh1hoF1sj4t485rDr3lvfQ2I//gacqkHUAPPDyQ0IJUx8iwU//Ev+W0S97l+PrS/MeEVN2SO1apDc=
  - AWS_DEFAULT_REGION: eu-west-1
