language: node_js
node_js:
  - '11'
notifications:
  email: false
cache:
  directories:
  - "~/.npm"
  - node_modules
before_deploy:
  - npm run test
  - npm run build
deploy:
  provider: s3
  access_key_id:
    secure: xB3hRFVgjr72PVmwRjisEpdIup38Nc+c0UKEtOF64vjxZ3GyPDDNyI1L2YMsnLHfmdstTQb1KTgMncX5qdkXKyKcv9ny7bDOeYfiMJ/64O/MmWcI/0S2HY+i4+wOLrR1LCGEwWz8Jh82AE92sO+znmJWiO3VOK+ceEwVjKVv3MHNKWeSuFp4JKjvi1Cm2gatmaA8KoQEZ+u4myU56unIIOGhEmGLS0tjj6CCVfUU3767HlqgqvQOkMbgTZR9ze/Z7uTIwCxHpD9twy//j9uJNqhiUbLQoIZLnXVOLvmkeK1XlIjVERu2a/7jdijbVtdgsEou2OQSwisASLOUBgtvZb0IyVpPlHEZXZPkCApcJrP5ZIfYuTCmBvL0DzUFC6A1e6RllTQyq1NOuE5PBXe/zZhclERywOjooei2CGVsa9liYJ5ilLvl+ywUC6O4iwLSoHwIzhj9uZO3L4SIDR2DrvqK3SuqfnHeG/I7zy6s5YAl4e+Cuwyx3QllWXt6bm31WbZgqholYXyzwg08lYrxhOKPGgPWMJ3vAiHeP7Q/gDxVnDSttFkRhSA2gXkFTwevSdnTHVokVy8AgqbPAEhk3ZcOVmX4DFK28r8TVz65bKWwQEzZUK5dm+76RPopT3lT5cqUfMeuq6+cfCMlDzOyUSbKrHJ7oZZo/6tzz2Dc5ys=
  secret_access_key:
    secure: no117ZCvCNDOgYY/xdU5Gr6Nu4o6LaeFEImeIlcTxyaTTJko/L/VEziqfAkURL+gRUvCvYnILOtBww/gJ+uRuUtNDoQWi6m8qHcTdteI5d9Qij/DwTz9ryuEEOBi6CaA3fLRB62pmRoqpCEKFY6ibDaP0PYN/JGvnEOXrF2XDg0rhi5+jPYNulDR2w8tHtrc7V/k8fSC5xjo46ZwShNJ4x2355IZtzx4VABP/oFJnclw3/FgH5eomKYQioqFckibJoadAalJLUM1sG3iZd1SitKLDUygGcFRax2FaQba/CsBEqL89e7VZ9yMrMlLlZqLScqeryMJupw6REeAb4GhbBah23HUqxq2/Jhuq/tyBpqAgM84d9Sw9QEG6x7l2ljsd8PIuFcHmgdekhB0gReRuS4DhnM0URsJkJC76gA9Doo11Ol08DP7Zkq195zCkL7uB9AQTVILNGd7G8lixdakKWQvgh0Hvlsk15u8Os03y2n3lR1vscoqnNslhoaV9RMMEcO6PibQYPxdxAcMTsdG/FxMPtOWwQpmhUWsPM9u9kCZHVSo+RIsJVPjP8uNRdSgs/jl1b7S8I5+80WUXL5P1BkdrpvugUeeEs7FEp9/plhtdNO1dfqPmD+INoGwh/zWb0Bk5jM37VMjWp3TIudrLM6eYTE1gcvoxvsfdYvG24Q=
  bucket: algebrain.io
  region: eu-west-1
  local_dir: build
  skip_cleanup: true
  on:
    branch: master
